---
- name: Preparing image with Docker and Nomad
  hosts: all
  become: yes
  gather_facts: false

  pre_tasks:
  - name: Install python2 for Ansible
    raw: bash -c "test -e /usr/bin/python || (apt -qqy update && apt install -qqy python-minimal)"
    register: output
    changed_when: output.stdout != ""
  - name: Gathering Facts
    setup:

  # Update distro
  tasks:
  - name: update apt
    apt:
      update_cache: yes

  # Prepare needed packages
  - name: Update all packages to the latest version
    apt:
      upgrade: dist
  - name: Install the package "apt-transport-https"
    apt:
      name: apt-transport-https
  - name: Install the package "ca-certificates"
    apt:
      name: ca-certificates
  - name: Install the package "curl"
    apt:
      name: curl
  - name: Install the package "software-properties-common"
    apt:
      name: software-properties-common
  - name: Install the package "gnupg-agent"
    apt:
      name: software-properties-common
  - name: Install the package "unzip"
    apt:
      name: unzip

  # Add GPG key for Docker
  - name: Add an apt key for Docker
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
  # Add Docker repo 
  - name: Add Docker repository 
    apt_repository:
      repo: deb https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable
      filename: /etc/apt/sources.list.d/docker
      state: present
  # Install Docker
  - name: Install Docker CE
    apt:
      name: docker-ce

  # Install Nomad
  - name: Install Nomad {{ nomad_version }}
    unarchive: 
      src: https://releases.hashicorp.com/nomad/{{ nomad_version }}/nomad_{{ nomad_version }}_linux_amd64.zip
      dest: /usr/local/bin
      owner: root
      group: root
      remote_src: yes
  - name: Create Nomad working directory
    file:
      path: "{{ item }}"
      state: directory
      mode: 755
      owner: root
      group: root
      recurse: yes
    loop:
      - /etc/nomad.d
      - /var/opt/nomad
  - name: Install Nomad systemd unit file
    template: src=templates/nomad.service.j2 dest=/etc/systemd/system/nomad.service
  - name: Reload Nomad systemd unit file
    systemd: 
      daemon_reload: yes

  # Install Consul
  - name: Install Consul {{ consul_version }}
    unarchive: 
      src: https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version }}_linux_amd64.zip
      dest: /usr/local/bin
      owner: root
      group: root
      remote_src: yes
  - name: Create Consul working directory
    file:
      path: "{{ item }}"
      state: directory
      mode: 755
      owner: root
      group: root
      recurse: yes
    loop:
      - /etc/consul.d
      - /var/opt/consul
  - name: Install Consul systemd unit file
    template: src=templates/consul.service.j2 dest=/etc/systemd/system/consul.service
  - name: Reload Consul systemd unit file
    systemd: 
      daemon_reload: yes

  # Cleanup
  - name: Remove useless packages from the cache
    apt:
      autoclean: yes
  - name: Remove dependencies that are no longer required
    apt:
      autoremove: yes
